# Generated by Django 4.0.4 on 2023-05-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resposavel', models.CharField(blank=True, default='', max_length=100)),
                ('descricao', models.TextField()),
                ('nivel', models.CharField(blank=True, default='', max_length=100)),
                ('situacao', models.CharField(blank=True, default='', max_length=100)),
                ('prioridade', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
