# Generated by Django 4.0.4 on 2023-05-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('responsavel', models.CharField(blank=True, default='', max_length=250)),
                ('nivel', models.IntegerField(choices=[(1, 1), (3, 3), (5, 5), (8, 8)])),
                ('situacao', models.CharField(max_length=12)),
                ('prioridade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
            ],
        ),
    ]
