# Generated by Django 4.0.4 on 2023-05-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0002_alter_task_options_remove_task_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='resposavel',
            new_name='responsavel',
        ),
        migrations.AlterField(
            model_name='task',
            name='nivel',
            field=models.IntegerField(choices=[('1', '1'), ('3', '3'), ('5', '5'), ('8', '8')], max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='prioridade',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
    ]
