# Generated by Django 4.0.4 on 2023-05-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0003_rename_resposavel_task_responsavel_alter_task_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='responsavel',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
